### ISSUE TITLE
Is this repo url a typo in README?

### ISSUE THREAD

**Issue by qichunren** [shakacode/react_on_rails_demo_ssr_hmr#35]
https://github.com/shakacode/react_on_rails_demo_ssr_hmr/blob/503ed4e084138b967cc458133b603de893c38e57/README.md?plain=1#L24

react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh  ->  [react_on_rails_demo_ssr_hmr](https://github.com/shakacode/react_on_rails_demo_ssr_hmr)

**Comment by justin808** [comment]
@qichunren yes! we renamed!

feel free to submit a PR!

**Comment by justin808** [comment]
fixed!
